name: Update badges

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
#       tags:
#         description: 'Test scenario tags'
#         required: false 
#         type: boolean
#       environment:
#         description: 'Environment to run tests against'
#         type: environment
#         required: true 

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: csj9703/csj9703@main
        with:
          GH_TOKEN: ${{secrets.GHTOKEN}}
          CREDLY_USER: shuji-chen
